# Generated by Django 4.2.4 on 2023-08-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_adv_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adv',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
